const constants = {
    ADD_API_KEY: "ADD_API_KEY",
    REMOVE_API_KEY: "REMOVE_API_KEY",
    //SET_API_KEY : "SET_API_KEY",
    GET_API_KEYS : "GET_API_KEYS",
    FETCH_ACTIVITIES : "FETCH_ACTIVITIES",
    DELETE_ACTIVITY: "DELETE_ACTIVITY",
    ADD_ACTIVITY : "ADD_ACTIVITY",
    FETCH_ENGINES : "FETCH_ENGINES",
    FETCH_APPS : "FETCH_APPS",
    DELETE_APP : "DELETE_APP",
    ADD_APP : "ADD_APP",
    FETCH_TOKEN : "FETCH_TOKEN",
    ADD_ERROR : "ADD_ERROR",
    CLEAR_ERROR : "CLEAR_ERROR",
    CREATE_WORKITEM: "CREATE_WORKITEM",
    CANCEL_WORKITEM: "CANCEL_WORKITEM"
}

export default constants;