const constants = {
    //API KEYS
    ADD_API_KEY: "ADD_API_KEY",
    REMOVE_API_KEY: "REMOVE_API_KEY",
    SET_CURRENT_API_KEY : "SET_CURRENT_API_KEY",
    //TOKEN
    RESET_TOKEN : "RESET_TOKEN",
    FETCH_TOKEN : "FETCH_TOKEN",
    SET_TOKEN : "SET_TOKEN",

    //engines
    RESET_ENGINES : "RESET_ENGINES",
    SET_ENGINES : "SET_ENGINES",
    FETCH_ENGINES : "FETCH_ENGINES",

    //activities
    RESET_ACTIVITIES : "RESET_ACTIVITIES",
    SET_ACTIVITIES : "SET_ACTIVITIES",
    FETCH_ACTIVITIES : "FETCH_ACTIVITIES",
    DELETE_ACTIVITY: "DELETE_ACTIVITY",
    ADD_ACTIVITY : "ADD_ACTIVITY",
    //apps
    RESET_APPS : "RESET_APPS",
    SET_APPS : "SET_APPS",
    FETCH_APPS : "FETCH_APPS",
    DELETE_APP : "DELETE_APP",
    ADD_APP : "ADD_APP",
    // Workitems
    ADD_WORKITEM : "ADD_WORKITEM",
    UPDATE_WORKITEM : "UPDATE_WORKITEM",
    REMOVE_WORKITEM : "REMOVE_WORKITEM",
    FETCH_WORKITEM : "FETCH_WORKITEM",
    STOPFETCH_WORKITEM : "STOPFETCH_WORKITEM",

    //OSS_STORAGE
    FETCH_BUCKETS : "FETCH_BUCKETS",
    SET_BUCKETS : "SET_BUCKETS",
    ADD_BUCKET : "ADD_BUCKET",
    FETCH_BUCKET : "FETCH_BUCKET",
    ADD_OBJECTS : "ADD_OBJECTS"


};

export default constants;